name: Release Extension

on:
  push:
    tags:
      - "*.*.*"

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update package.json version to match tag
        run: |
          VERSION=$(echo "${GITHUB_REF_NAME}" | sed 's/^v//')
          jq ".version = \"${VERSION}\"" package.json > package.tmp.json
          mv package.tmp.json package.json

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install vsce
        run: npm install -g vsce

      - name: Install dependencies
        run: pnpm install

      - name: Build and package extension
        run: pnpm run build

      - name: Extract latest changelog entry
        id: changelog
        run: |
          VERSION=$(echo "${GITHUB_REF_NAME}" | sed 's/^v//')
          awk "/## \\[${VERSION}\\]/ {flag=1; next} /## \[/ {flag=0} flag" CHANGELOG.md > RELEASE_BODY.md
          echo "RELEASE_BODY<<EOF" >> $GITHUB_ENV
          cat RELEASE_BODY.md >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Publish to VS Code Marketplace
        run: vsce publish -p ${{ secrets.VSCE_PAT }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: v${{ github.ref_name }}
          body_path: RELEASE_BODY.md
          files: |
            *.vsix
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
